# This playbook is for setting up filebeat
# You can run this playbook with the following command:
# sudo ansible-playbook -i hosts/elastic.hosts playbooks/filebeat.yml

- hosts: centos 
  remote_user: root
  become: true
  roles:
    - role: reboot      
