---
########################################################
# Set up Kibana
########################################################
- name: Install kibana
  yum: 
    name: kibana-{{ elasticsearch_version }}
    state: latest 
    update_cache: yes

- name: Create kibana config
  template:
    src: kibana.config.j2
    dest: /etc/kibana/kibana.yml
    backup: yes

- name: Force systemd to reread configs
  systemd: daemon_reload=yes

- name: Enable kibana.service
  systemd:
    name: kibana.service
    enabled: yes
    
- name: permit port {{ kibana_port }} for kibana
  firewalld: 
    port: "{{ kibana_port }}/tcp"
    state: enabled
    permanent: yes

- name: restart firewalld service
  systemd:
    name: firewalld
    state: restarted


