---
########################################################
# Set up Java 8
########################################################

- name: Install Oracle openJDK 8
  yum: 
    name: java-1.8.0-openjdk.x86_64
    state: latest
